[package]
name = "rustkids"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
json = "0.12.4"
mathru = "0.15.3"
ndarray = "0.15.6"
serde = "1.0.195"
gflags = "0.3.12"
